# Installs AWS client using instructions on the following Amazon document:
# 

- name: dump RHEL user names that awscli will be installed for
  debug:
    msg: "awscli_users: {{awscli_users}}"

- name: installing aws-cli
  include_tasks: install-awscli.yml
  vars:
    - aws_user: "{{item}}"
  with_items: "{{awscli_users}}"  
  tags: [awscli]

