# Installing AWS CLI is the simplest via PIP.
#
# - use EPEL approach
# 

- name: prepare repo and install pip using EPEL
  include_tasks: install-pip-using-epel.yml
  become: yes
  become_user: root
  tags: [awscli]

- debug:
    msg: "awscli_users: {{awscli_users}}"

- name: installing aws-cli
  include_tasks: install-awscli.yml
  vars:
    - aws_user: "{{item}}"
  loop: "{{awscli_users}}"  
  tags: [awscli]

