---
# This is only example playbook.
# It contains all roles from this repository.
# You should copy it and use different host from your Inventory file
# All files in playbooks directory will be ignored, except of this file
- hosts: dev01
  become: yes
  become_user: root
  roles:
#    - ../roles/centos
#    - ../roles/ntp
#    - ../roles/openssl
#    - ../roles/git
#    - ../roles/httpd
#    - ../roles/nodejs
#    - ../roles/awscli
#    - ../roles/mysql
#    - ../roles/php
#    - ../roles/datadog
#    - ../roles/mongodb
#    - ../roles/letsencrypt
#    - ../roles/nginx
#    - ../roles/redis

  vars_files:
    - ../vars/my-vars.yml

# You can also include custom variable files that will override any defaults from roles

